# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66580e211aa95ed92f2b77debc70e77c8cffaf36fbd0e670e0d48d24561910ea6f016a837ad7f88b61dd865de35dd9128e3fc1ebdeaa4e7b4858ff85c894cca8

test:
  secret_key_base: b45740eb2158b316717e3462b027e570c6d803b459cdc26ddf910ff1dad6c98cdc61fc1b1e161a09b2bbbd177391d861670c99009f744b0754c06d5ed7182c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
